### ISSUE TITLE
default error message is misleading

### ISSUE THREAD

**Issue by Plagiatus** [JirkaDellOro/MingiDB#1]
the default error message when no parameters are given prints "no collection specified", eventhough the actual first issue is that no command was specified. 

If a nonexisting command was specified, you only get info about that when you provide a collection.

Only if a valid command was given which requires a collection name to be specified should that error show up.

-----

input: `?`  
expected output: `no command specified`
actual output: `no collection specified`

❌ 

-----

input: `?command=foo`  
expected output: `unknown command`  
actual output: `no collection specified`

❌ 

-----

input: `?command=foo&collection=bar`  
expected output: `unknown command`
actual output: `unknown command`

✅ 

-----

input: `?command=find`  
expected output: `no collection specified`  
actual output: `no collection specified`

✅

**Comment by JirkaDellOro** [comment]
fixed part 1, won't fix 2
