### ISSUE TITLE
Bug bei einen Dokument ohne Daten

### ISSUE THREAD

**Issue by Duvid19** [JirkaDellOro/MingiDB#3]
Wenn man in eine Collection ein neues Dokument ohne Daten bzw. Inhalt hinzufügt, kommt es zu einen Bug das dieses Dokument gefunden wird, allerdings nicht gelöscht werden kann.

![image](https://user-images.githubusercontent.com/91938270/182856172-0d54ab8b-4a1e-40f4-99a0-9d31b6b5e9d9.png)

![image](https://user-images.githubusercontent.com/91938270/182856214-b4acc9df-6f78-4c13-bd06-7365f9954e22.png)

**Comment by JirkaDellOro** [comment]
up for testing
